### ISSUE TITLE
pygls new version incompatible with hyuga

### ISSUE THREAD

**Issue by ghost** [sakuraiyuta/hyuga#15]
Hi,

I am trying to use Hyuga with LunarVim. Hyuga is incompatible with the current version of pygls 1.0.2. The log file is hard to read (formatting); here is the output from running hyuga directly.

hy /home/claude/Python-3.11.4/lib/python3.11/site-packages/hyuga/server.hy
Traceback (most recent call last):
  File "/home/claude/Python-3.11.4/bin/hy", line 8, in <module>
    sys.exit(hy_main())
             ^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/home/claude/Python-3.11.4/lib/python3.11/site-packages/hyuga/server.hy", line 4, in <module>
    (import pygls.lsp.methods [COMPLETION
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pygls.lsp.methods'

I tried downgrading pygls to 0.13.1 and got different errors.

Please point me in the right direction.

Thanks.

P. S. Debian 12 on AMD64, Hy 0.27.0

**Comment by ghost** [comment]
Hi,

After editing hyuga-master/hyuga/server.hy to use the new names (see pygls docs, link below), funcparserlib/parser.py complains (see traceback below).

Fixing this could be straightforward: comparing traceback info with recent changes to Hy or funcparserlib and adjusting hyuga. It could also be a descent into a rabbit hole.

Any hints?

Thanks.

P. S.  I am using Hy 0.27.0 with hyrule 0.4.0

https://pygls.readthedocs.io/en/latest/pages/migrating-to-v1.html?highlight=lsp%20methods

Traceback (most recent call last):
  File "/home/claude/Python-3.11.4/lib/python3.11/site-packages/hy/macros.py", line 66, in hyx_Xfull_stopX
    parse_tree = pattern.parse(args)
                 ^^^^^^^^^^^^^^^^^^^
  File "/home/claude/Python-3.11.4/lib/python3.11/site-packages/funcparserlib/parser.py", line 221, in parse
    (tree, _) = self.run(tokens, State(0, 0, None))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/claude/Python-3.11.4/lib/python3.11/site-packages/funcparserlib/parser.py", line 312, in ignored_right
    _, s3 = other.run(tokens, s2)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/claude/Python-3.11.4/lib/python3.11/site-packages/funcparserlib/parser.py", line 770, in ignored
    v, s2 = run(tokens, s)
            ^^^^^^^^^^^^^^
  File "/home/claude/Python-3.11.4/lib/python3.11/site-packages/funcparserlib/parser.py", line 534, in finished
    raise NoParseError("got unexpected token", s2)
funcparserlib.parser.NoParseError: got unexpected token: hy.models.Symbol('None'), expected: some(...)

**Comment by sakuraiyuta** [comment]
I apologize for the delayed response.
Currently, I am swamped with daily tasks and have not been able to fully grasp the content yet.
I will make sure to check it by next week.

**Comment by sakuraiyuta** [comment]
fixed in v0.1.2
