### ISSUE TITLE
break

### ISSUE THREAD

**Issue by Freed-Wu** [sakuraiyuta/hyuga#23]
```sh
❯ hyuga
Traceback (most recent call last):
  File "/usr/bin/hyuga", line 5, in <module>
    from hyuga.__main__ import main
  File "/usr/lib/python3.12/site-packages/hyuga/__main__.py", line 3, in <module>
    from .server import start
  File "/usr/lib/python3.12/site-packages/hyuga/server.hy", line 12, in <module>
    (import hyuga.api *)
     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/hyuga/api.hy", line 8, in <module>
    (import hyuga.global [$GLOBAL])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "/usr/lib/python3.12/site-packages/hy/importer.py", line 123, in _hy_source_to_code
    data = hy_compile(hy_tree, module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/hy/compiler.py", line 882, in hy_compile
    result = compiler.compile(tree)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/hy/compiler.py", line 420, in compile
    raise e
  File "/usr/lib/python3.12/site-packages/hy/compiler.py", line 411, in compile
    ret = self.compile_atom(tree)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/hy/compiler.py", line 405, in compile_atom
    return Result() + _model_compilers[type(atom)](self, atom)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/hy/compiler.py", line 494, in _compile_branch
    last = self.compile(node)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/hy/compiler.py", line 420, in compile
    raise e
  File "/usr/lib/python3.12/site-packages/hy/compiler.py", line 411, in compile
    ret = self.compile_atom(tree)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/hy/compiler.py", line 405, in compile_atom
    return Result() + _model_compilers[type(atom)](self, atom)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/hy/compiler.py", line 566, in compile_expression
    expr = macroexpand(expr, self.module, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/hy/macros.py", line 397, in macroexpand
    obj = m(
          ^^
  File "/usr/lib/python3.12/site-packages/hy/macros.py", line 73, in require
    return fn(_hy_compiler, expr, name, *parse_tree)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/hy/core/result_macros.py", line 1905, in compile_require
    elif (rest or not readers) and require(
                                   ^^^^^^^^
  File "/usr/lib/python3.12/site-packages/hy/macros.py", line 265, in require
    raise HyRequireError(
hy.errors.HyRequireError: Could not require name assoc from <module 'hyrule.collections' from '/usr/lib/python3.12/site-packages/hyrule/collections.hy'>
```

- hy: 1.0.0
- hyrule: 0.7.0
- hyuga: 0.2.1
- toolz: 1.0.0

**Comment by sakuraiyuta** [comment]
Can you try to update hyuga version `1.0.0`?

https://pypi.org/project/hyuga/

**Comment by Freed-Wu** [comment]
Now it works. TIA!
